databases:
  - name: expence-db
    databaseName: expence_db
    plan: free

services:
  - type: web
    name: expence-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expence-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "10080"
